### ISSUE TITLE
Include labeling with feature requests

### ISSUE THREAD

**Issue by b-long** [archetyped/winning-user-support#1]
Here's an example : 

https://github.com/archetyped/winning-user-support/issues/new?title=Feature%20Request%3A%20&labels=enhancement

**Comment by archetyped** [comment]
Hi, including labels would be useful, but unfortunately labels can only be added by authorized contributors to a repo.  If GitHub adds the ability for any user to create and assign labels to an issue, I'll definitely update the links.

Thanks :)
